python STC_tracker.py David2 &
python STC_tracker.py FaceOcc2 &
python STC_tracker.py David &
python STC_tracker.py Bolt &
python STC_tracker.py Crossing &
python STC_tracker.py Fish &
python STC_tracker.py FaceOcc1 &
python STC_tracker.py Singer2 &
python STC_tracker.py Subway &
python STC_tracker.py Deer &
